"""Build the Neovim presentation from the six canonical portfolio pages."""

from html import escape
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
PAGES = (
    ("index", "Home", "readme"),
    ("experience", "Experience", "experience"),
    ("research", "Research", "research"),
    ("projects", "Projects", "projects"),
    ("teaching", "Teaching", "teaching"),
    ("competitive-programming", "Competitive Programming", "contests"),
)


def build():
    for slug, title, buffer in PAGES:
        source = (ROOT / f"{slug}.html").read_text()
        match = re.search(r'<main\b[^>]*>(.*?)</main>', source, re.S)
        if not match:
            raise ValueError(f"Missing main content: {slug}.html")
        content = match.group(1)
        for other, _, _ in PAGES:
            content = content.replace(f'href="{other}.html', f'href="{other}_nvim.html')
        description = re.search(r'name="description"\s+content="([^"]+)"', source).group(1)
        files, tabs = [], []
        for other, label, filename in PAGES:
            current = ' aria-current="page"' if other == slug else ''
            files.append(f'<a href="{other}_nvim.html"{current}><span aria-hidden="true">≡</span> {label}</a>')
            tabs.append(f'<a href="{other}_nvim.html"{current} aria-label="{label}">{filename}.md</a>')
        html = f'''<!doctype html>
<!-- Generated by scripts/build_nvim.py; edit {slug}.html for shared content. -->
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="theme-color" content="#fbf1c7">
  <meta name="description" content="{description}">
  <meta name="author" content="Ronaldo Franco Jaldin">
  <title>{escape(title)} — Ronaldo Franco Jaldin · Neovim</title>
  <link rel="icon" href="assets/images/favicon.svg" type="image/svg+xml">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;500;600;700&amp;display=swap" rel="stylesheet">
  <link rel="stylesheet" href="assets/css/nvim.css">
</head>
<body>
  <a class="skip-link" href="#content">Skip to content</a>
  <header class="window-bar">
    <a class="brand" href="index_nvim.html"><span class="nvim-mark" aria-hidden="true">N</span> ronaldo / portfolio</a>
    <a class="theme-switch" href="{slug}.html">Reading view ↗</a>
  </header>
  <div class="workspace">
    <aside class="explorer" aria-label="Portfolio explorer">
      <p class="explorer-heading">EXPLORER</p>
      <p class="folder"><span aria-hidden="true">⌄</span> ~/portfolio</p>
      <nav aria-label="Main navigation">
        {' '.join(files)}
      </nav>
      <div class="explorer-links">
        <p class="explorer-heading">DOCUMENTS</p>
        <a href="assets/docs/ronaldo-franco-industry-cv.pdf" download>↓ industry-cv.pdf</a>
        <a href="assets/docs/ronaldo-franco-academic-cv.pdf" download>↓ academic-cv.pdf</a>
      </div>
      <a class="pet-note" href="projects_nvim.html#petsadhd">
        <span aria-hidden="true" class="pixel-pet"> ▄▀▀▄\n▐ ▀▀ ▌\n ▀▄▄▀</span>
        <span>PetsADHD<span class="pet-caption">a little company while coding</span></span>
      </a>
      <p class="explorer-foot">Cochabamba, Bolivia<br>ML · research · teaching</p>
    </aside>
    <div class="editor">
      <nav class="buffer-tabs" aria-label="Open pages">{' '.join(tabs)}</nav>
      <div class="breadcrumb" aria-hidden="true">portfolio <span>/</span> {buffer}.md</div>
      <main id="content" tabindex="-1">
{content}
      </main>
      <div class="end-of-buffer" aria-hidden="true">~<br>~<br>~</div>
      <footer class="page-footer">© 2026 Ronaldo Franco Jaldin <a href="#content">Back to top ↑</a></footer>
    </div>
  </div>
  <footer class="statusline" aria-label="Theme information">
    <span class="mode">NORMAL</span><span class="status-file">{buffer}.md</span>
    <span class="status-theme">gruvbox · light</span><span class="encoding">UTF-8</span><a href="#content">↑ Top</a>
  </footer>
</body>
</html>
'''
        (ROOT / f"{slug}_nvim.html").write_text("\n".join(line.rstrip() for line in html.splitlines()) + "\n")
    print(f"Built {len(PAGES)} Neovim pages from canonical content.")


if __name__ == "__main__":
    build()
